name: Terraform Test

on:
  pull_request:

jobs:
  terraform-test:
    name: Terraform Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Initialize Terraform
        run: terraform init

      - name: Run Terraform Test
        run: terraform test
